description: Studio d'enregistrement, de mixage, de mastering et de sonorisation live pour le metal, le punk, le doom, le sludge, la pop, le folk et le rock.
email: lesproductionsduchauve@gmail.com
socials:
  - name: YouTube
    url: https://www.youtube.com/@YvesDeRoeck
  - name: Facebook
    url: https://www.facebook.com/Yoorwell/
  - name: Bandcamp
    url: https://lesprodchauve.bandcamp.com
